### ISSUE TITLE
PM - Check if run exists in Swestore

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/pm#45]
Now it will crash if the run already exists in Swestore:

```
ERROR: putUtil: put error for /ssUppnexZone/proj/a2010002/141120_M01548_0038_000000000-AB8D9.tar.bz2, status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG
```

**Comment by senthil10** [comment]
@guillermo-carrasco : I have always wondered about this, would something like this work ?

```
def is_in_swestore(run_name,ext="tar.bz2"):
    cmd = ['ils', '{}.{}'.format(run_name,ext)]
    called = subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
    out,err = called.communicate()
    if out:
        return True
    else:
        return False
```

**Comment by guillermo-carrasco** [comment]
yeah that would do the work. However instead of checking explicitely, I would just examine the output and if the status is -312000, then say the the run is already in swestore and skip it.

But yeah your solution would work perfectly fine as well.

**Comment by senthil10** [comment]
what you suggest is even simpler :joy:
